version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "spotless-plugin-gradle" # likely to require reformatting of code
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "America/New_York"
    target-branch: "main"
    reviewers:
      - "@DataBiosphere/broad-core-services"
    labels:
      - "dependency"
      - "gradle"
    commit-message:
      prefix: "[CORE-69]"
    ignore:
      - dependency-name: "au.com.dius.pact*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
