# All environment variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  db:
    host: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:${DATABASE_PORT:5432}
    init: ${INIT_DB:false}
    stairway:
      name: ${STAIRWAY_DATABASE_NAME:profile_stairway}
      pass: ${STAIRWAY_DATABASE_USER_PASSWORD:stairwaypwd}
      user: ${STAIRWAY_DATABASE_USER:stairwayuser}
    profile:
      name: ${DATABASE_NAME:profile_db}
      pass: ${DATABASE_USER_PASSWORD:dbpwd}
      user: ${DATABASE_USER:dbuser}
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  sam:
    basePath: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org/}
    adminsGroupEmail: ${SAM_ADMINS_GROUP_EMAIL:admin-group}
  azure:
    managedAppClientId: ${MANAGED_APP_CLIENT_ID:app-client}
    managedAppClientSecret: ${MANAGED_APP_CLIENT_SECRET:app-secret}
    managedAppTenantId: ${MANAGED_APP_TENANT_ID:app-tenant}
  sentry:
    dsn: ${SENTRY_DSN:}
    environment: ${DEPLOY_ENV:}

# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the BPM test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
spring.config.import: optional:file:build/resources/main/generated/local-properties.yaml

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: profile
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/api/

profile:
  ingress:
    # Default value that's overridden by Helm.
    domain-name: localhost:8080

  job:
    max-threads: 4
    polling-interval-seconds: 1
    resource-id: mc-terra-billing-profile-manager
    timeout-seconds: 1800

  sam:
    base-path: ${env.sam.basePath}
    admins-group-email: ${env.sam.adminsGroupEmail}

  stairway-database:
    password: ${env.db.stairway.pass}
    uri: ${env.db.host}/${env.db.stairway.name}
    username: ${env.db.stairway.user}

  status-check:
    enabled: true
    polling-interval-seconds: 60
    startup-wait-seconds: 5
    staleness-threshold-seconds: 125

  profile-database:
    initialize-on-start: ${env.db.init}
    password: ${env.db.profile.pass}
    upgrade-on-start: true
    uri: ${env.db.host}/${env.db.profile.name}
    username: ${env.db.profile.user}

  azure:
    managed-app-clientId: ${env.azure.managedAppClientId}
    managed-app-client-secret: ${env.azure.managedAppClientSecret}
    managed-app-tenant-id: ${env.azure.managedAppTenantId}

    application-offers:
      - name: terra-dev-preview
        publisher: thebroadinstituteinc1615909626976
        authorized-user-key: authorizedTerraUser

    required-providers:
      - "Microsoft.Storage"
      - "Microsoft.Compute"
      - "Microsoft.Authorization"
      - "Microsoft.Batch"
      - "Microsoft.Compute"
      - "Microsoft.OperationalInsights"
      - "Microsoft.OperationsManagement"
      - "microsoft.insights"
      - "Microsoft.Network"
      - "Microsoft.DBforPostgreSQL"
      - "Microsoft.ContainerRegistry"
      - "Microsoft.KeyVault"
      - "Microsoft.ContainerService"

  sentry:
    dsn: ${env.sentry.dsn}
    environment: ${env.sentry.environment}

terra.common:
  kubernetes:
    in-kubernetes: false
  stairway:
    cluster-name-suffix: profile-stairway
    force-clean-start: false # ${env.db.init}
    max-parallel-flights: 50
    migrate-upgrade: true
    quiet-down-timeout: 30s
    terminate-timeout: 30s
    tracing-enabled: true
    retention-check-interval: 1d
    completed-flight-retention: 7d

  tracing:
    stackdriverExportEnabled: ${env.tracing.exportEnabled}
    samplingRate: ${env.tracing.samplingRate}
