name: Publish branch image
on:
  push:
    branches:
      - "arh-exp"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/publish-branch.yaml"


env:
  GOOGLE_PROJECT: broad-dsp-gcr-public
  SERVICE_NAME: ${{ github.event.repository.name }}

jobs:
  publish-image:
    uses: ./.github/workflows/publish.yml
    secrets: inherit