name: Tag
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      dry-run:
        description: "Determine the next version without tagging the branch. The workflow can use the outputs new_tag and tag in subsequent steps. Possible values are true and false (default)"
        default: false
        required: false
        type: string
      print-tags:
        description: "Echo tags to console"
        default: true
        required: false
        type: string
    outputs:
      tag:
        description: "The value of the latest tag after running this action"
        value: ${{ jobs.tag-job.outputs.tag }}
      new-tag:
        description: "The value of the newly created tag"
        value: ${{ jobs.tag-job.outputs.new-tag }}
    secrets:
      BROADBOT_TOKEN:
        required: true

jobs:
  tag-job:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      new-tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }} # this allows the push to succeed later
      - name: Bump the tag to a new version
        # https://github.com/DataBiosphere/github-actions/tree/master/actions/bumper
        uses: databiosphere/github-actions/actions/bumper@bumper-0.0.6
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
          HOTFIX_BRANCHES: hotfix.*
          DEFAULT_BUMP: patch
          DRY_RUN: ${{ inputs.dry-run }}
          RELEASE_BRANCHES: main
          VERSION_FILE_PATH: settings.gradle
          VERSION_LINE_MATCH: "^\\s*gradle.ext.releaseVersion\\s*=\\s*'.*'"
          VERSION_SUFFIX: SNAPSHOT
      - name: Echo tags to console
        if: ${{ inputs.print-tags == 'true' }}
        run: |
          echo "Newly created version tag: '${{ steps.tag.outputs.new_tag }}'"
          echo "Value of latest tag in settings.gradle after running the action: '${{ steps.tag.outputs.tag }}'"
          cat settings.gradle
