name: Verify consumer pacts
# The purpose of this workflow is to verify ANY consumer contract(s) dependent on BPM provider using Pact framework.
#
# This workflow is triggered when
#
# 1. Consumer makes a change that results in a new pact published to Pact Broker (will verify ONLY the changed pact and publish the verification results back to the broker)
# 2. Provider makes a change (runs verification tests against ALL DEPLOYED consumer pact versions and publishes corresponding verification results)
#
#
# The workflow requires Pact broker credentials
# - PACT_BROKER_USERNAME - the Pact Broker username
# - PACT_BROKER_PASSWORD - the Pact Broker password
on:
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  merge_group:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  workflow_dispatch:
    inputs:
      pb-event-type:
        description: 'the Pact Broker event type that triggers this workflow'
        required: true
        type: string
      consumer-name:
        description: 'the consumer name'
        required: true
        type: string
      consumer-version-number:
        description: 'the version number of the most recent consumer version associated with the pact content'
        required: true
        type: string
      provider-version-number:
        description: 'the provider version number for the verification result'
        required: true
        type: string
      consumer-version-tags:
        description: 'the list of tag names for the most recent consumer version associated with the pact content, separated by ", "'
        required: true
        type: string
      consumer-version-branch:
        description: 'the name of the branch for most recent consumer version associated with the pact content'
        required: true
        type: string
      provider-version-branch:
        description: 'the name of the branch for the provider version associated with the verification result'
        required: true
        type: string
      consumer-labels:
        description: 'the list of labels for the consumer associated with the pact content, separated by ", "'
        required: false
        type: string
      provider-labels:
        description: 'the list of labels for the provider associated with the pact content, separated by ", "'
        required: false
        type: string
      pact-url:
        description: 'the "permalink" URL to the newly published pact (the URL specifying the consumer version URL, rather than the "/latest" format'
        required: true
        type: string

env:
  CAN_I_DEPLOY_RUN_NAME: 'can-i-deploy-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}'
  RELEASE_BRANCH: 'main'

jobs:

  #################################################
  # VERSIONING, BRANCH MANAGEMENT, INIT AND SETUP #
  #################################################

  bump-check:
    runs-on: ubuntu-latest
    outputs:
      is-bump: ${{ steps.skiptest.outputs.is-bump }}
    steps:
      - uses: actions/checkout@v3
      - name: Skip version bump merges
        id: skiptest
        uses: ./.github/actions/bump-skip
        with:
          event-name: ${{ github.event_name }}

  init-github-context:
    runs-on: ubuntu-latest
    needs: [ bump-check ]
    if: ${{ needs.bump-check.outputs.is-bump == 'no' }}
    outputs:
      repo-branch: ${{ steps.extract-branch.outputs.repo-branch }}
      verify-provider-side-contracts-only: ${{ steps.set-environment.outputs.verify-provider-side-contracts-only }}

    steps:
      - id: extract-branch
        run: |
          GITHUB_EVENT_NAME=${{ github.event_name }}
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            GITHUB_REF=${{ github.ref }}
            GITHUB_SHA=${{ github.sha }}
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            GITHUB_REF=refs/heads/${{ github.head_ref }}
            GITHUB_SHA=${{ github.event.pull_request.head.sha }}
          elif [[ "$GITHUB_EVENT_NAME" == "merge_group" ]]; then
            GITHUB_REF=refs/heads/${{ github.head_ref }}
          elif [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            # GITHUB_REF=${{ github.ref }} # The Git Ref that this workflow runs on
          else
            echo "Failed to extract branch information"
            exit 1
          fi
          echo "repo-branch=${GITHUB_REF/refs\/heads\//""}" >> $GITHUB_OUTPUT
          echo "repo-version=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: set various output settings
        id: set-environment
        run: |
          echo "verify-provider-side-contracts-only=${{ inputs.pb-event-type != '' }}" >> $GITHUB_OUTPUT

      - name: Echo repo and branch information
        run: |
          echo "repo-owner=${{ github.repository_owner }}"
          echo "repo-name=${{ github.event.repository.name }}"
          echo "repo-branch=${{ steps.extract-branch.outputs.repo-branch }}"
          echo "repo-version=${{ steps.extract-branch.outputs.repo-version }}"

  # We only need a new version tag when this workflow is triggered by opening, updating a PR or PR merge.
  # When triggered by a Pact Broker webhook, the provider version (GIT hash or release tag)
  # is already included in the payload, then a new version tag wouldn't be needed.
  #
  regulated-tag-job:
    needs: [ init-github-context ]
    if: ${{ needs.bump-check.outputs.is-bump == 'no' }}
    uses: ./.github/workflows/tag.yml
    with:
      # The 'ref' parameter ensures that the provider version is postfixed with the HEAD commit of the PR branch,
      # facilitating cross-referencing of a pact between Pact Broker and GitHub.
      ref: ${{ needs.init-github-context.outputs.repo-branch || '' }}
      # The 'dry-run' parameter prevents the new tag from being dispatched.
      dry-run: true
      release-branches: main
    secrets: inherit

  #################################        
  # CONSUMER CONTRACT PUBLISHING #
  #################################

  run-consumer-contract-tests:
    runs-on: ubuntu-latest
    needs: [ bump-check, init-github-context ]
    if: ${{ needs.init-github-context.outputs.verify-provider-side-contracts-only == false }}
    outputs:
      pact-paths: ${{ steps.locate-pacts.outputs.pact-paths }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run consumer tests
        run: ./gradlew pactTests
      - name: Locate pact files
        id: locate-pacts
        run: |
          pactPaths=$(find "$PACTS_OUTPUT_DIR" -type f -name "*.json" | jq -cnR "[inputs]")
          echo "pact-paths=$pactPaths" >> $GITHUB_OUTPUT
      - name: Upload pact files to artifact
        id: upload-pacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACTS_ARTIFACT }}
          path: ${{ env.PACTS_OUTPUT_DIR }}
          retention-days: 1

  publish-contracts:
    runs-on: ubuntu-latest
    needs: [ bump-check, init-github-context, run-consumer-contract-tests, regulated-tag-job ]
    strategy:
      matrix:
        pact_path: ${{ fromJson(needs.run-consumer-contract-tests.outputs.pact-paths) }}
    if: ${{ needs.bump-check.outputs.is-bump == 'no' }}
    steps:
      - name: Download pact files from artifact
        id: download-pacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACTS_ARTIFACT }}
          path: ${{ env.PACTS_OUTPUT_DIR }}

      - name: Encode pact as non-breaking base64 string
        id: encode-pact
        run: |
          nonBreakingB64=$(cat "${{ matrix.pact_path }}" | base64 -w 0)
          echo "pact-b64=${nonBreakingB64}" >> $GITHUB_OUTPUT  

      - name: Dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v4.0.0
        with:
          run-name: "${{ env.PUBLISH_CONTRACTS_RUN_NAME }}-${{ matrix.pact_path }}"
          workflow: .github/workflows/publish-contracts.yaml
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN }} # github token for access to kick off a job in the private repo
          inputs: '{
            "run-name": "${{ env.PUBLISH_CONTRACTS_RUN_NAME }}-${{ matrix.pact_path }}",
            "pact-b64": "${{ steps.encode-pact.outputs.pact-b64 }}",
            "repo-owner": "${{ github.repository_owner }}",
            "repo-name": "${{ github.event.repository.name }}",
            "repo-branch": "${{ needs.init-github-context.outputs.repo-branch }}" ,
            "release-tag": "${{ needs.regulated-tag-job.outputs.new-tag }}"
            }'

  ###############################        
  # PROVIDER VERIFICATION STEPS #
  ###############################

  verify-consumer-pact:
    needs: [ bump-check, regulated-tag-job, init-github-context ]
    if: ${{ needs.bump-check.outputs.is-bump == 'no' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      CURRENT_BRANCH: ${{needs.init-github-context.outputs.repo-branch}}
    outputs:
      provider-version: ${{ steps.verification-test.outputs.provider-version }}

    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set local environment variables
        echo "CURRENT_BRANCH=${{ needs.init-github-context.output.repo-branch }}" >> $GITHUB_ENV

      - name: Capture webhook event payload as envvars
        if: ${{ inputs.pb-event-type != '' }}
        run: |
          echo "pb-event-type=${{ inputs.pb-event-type }}"
          echo "consumer-name=${{ inputs.consumer-name }}"

          # The consumer-version-branch and consumer-version-number identify the most recent
          # consumer branch and version associated with the pact content.
          echo "consumer-version-branch/consumer-version-number=${{ inputs.consumer-version-branch }}/${{ inputs.consumer-version-number }}"

          # The provider-version-number represents the provider version number in the webhook event payload.
          # This corresponds to the GitHub release tag recorded by Sherlock for the corresponding
          # deployment environment (dev, staging, and prod).
          echo "provider-version-branch/provider-version-number=${{ inputs.provider-version-branch }}/${{ inputs.provider-version-number }}"

          # The pact-url is included here in case future pact4s client supports it.
          echo "pact-url=${{ inputs.pact-url }}"

          # Save webhook event parameters as envvars
          echo "PROVIDER_BRANCH=${{ inputs.provider-version-branch }}" >> $GITHUB_ENV
          echo "PROVIDER_TAG=${{ inputs.provider-version-number }}" >> $GITHUB_ENV
          echo "CONSUMER_BRANCH=${{ inputs.consumer-version-branch }}" >> $GITHUB_ENV
          echo "CONSUMER_NAME=${{ inputs.consumer-name }}" >> $GITHUB_ENV
          echo "CONSUMER_VERSION=${{ inputs.consumer-version-number }}" >> $GITHUB_ENV

      # if pb-event-type is null, then do this
      # basically, PR flow.
      - name: Set PROVIDER_VERSION envvar
        run: |
          # The PROVIDER_VERSION envvar is used to identify the provider version
          # for publishing the results of provider verification.
          if [[ -z "${{ inputs.pb-event-type }}" ]]; then
            echo "PROVIDER_BRANCH=${{ env.CURRENT_BRANCH }}" >> $GITHUB_ENV
            echo "PROVIDER_VERSION=${{ needs.regulated-tag-job.outputs.new-tag }}" >> $GITHUB_ENV
          else
            echo "PROVIDER_VERSION=${{ env.PROVIDER_TAG }}" >> $GITHUB_ENV
          fi
    
      # if PROVIDER_TAG exists then use it, otherwise use CURRENT_BRANCH
      # which was extracted in the last step.
      # CURRENT_BRANCH should usualy bee pr versions, can be mainline versin on merge.
      # PROVIDER_TAG would correspond to whatever is on dev/staging/prod something semvet
      - name: Switch to appropriate provider branch
        run: |
          echo "This workflow has been triggered by '${{ github.event_name }}' event."

          # If the PROVIDER_TAG envvar exists, switch to the corresponding tag.
          # This condition is true when the workflow is triggered by a Pact Broker webhook event.
          if [[ -n "${{ env.PROVIDER_TAG }}" ]]; then
            echo "git checkout tags/${{ env.PROVIDER_TAG }}"
            git checkout tags/${{ env.PROVIDER_TAG }}

          # Otherwise, switch to CURRENT_BRANCH if the workflow has been triggered by a
          # PR commit or merge onto the main branch.
          elif [[ "${{ github.event_name }}" == "pull_request" ]] || [[ "${{ github.event_name }}" == "push" ]]; then
            echo "git checkout ${{ env.CURRENT_BRANCH }}"
            git checkout ${{ env.CURRENT_BRANCH }}
          fi

          # Echo the HEAD commit of the provider branch that has been switched to.
          echo "git rev-parse HEAD"
          git rev-parse HEAD
    # everything above this line should go into init github context. ^^^^
    
    # Break out this into it's own job as this is the actual run
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ github.ref }}-${{ github.sha }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ github.ref }}

      - name: Verify consumer pacts and publish verification status to Pact Broker
        id: verification-test
        # The PACT_... envvars are being consumed by build.gradle to configure the
        # following System properties (https://docs.pact.io/implementation_guides/jvm/docs/system-properties)
        # pact.provider.{branch, version}
        # pactbroker.{host, scheme}
        # pactbroker.auth.{username, password}
        # If no CONSUMER_BRANCH/VERSION given, will just verify all deployed consumer versions.
        env:
          PACT_BROKER_URL: pact-broker.dsp-eng-tools.broadinstitute.org
          PACT_PROVIDER_VERSION: ${{ env.PROVIDER_VERSION }}
          PACT_PROVIDER_BRANCH:  ${{ env.PROVIDER_BRANCH }}
          PACT_BROKER_USERNAME:  ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD:  ${{ secrets.PACT_BROKER_PASSWORD }}
        run: |
          echo "provider-version=${{ env.PACT_PROVIDER_VERSION }}" >> $GITHUB_OUTPUT
          echo "env.CONSUMER_BRANCH=${{ env.CONSUMER_BRANCH }}   # This reflects the consumer branch for pact verification (generated by Pact Broker)"
          echo "env.PROVIDER_BRANCH=${{ env.PROVIDER_BRANCH }}   # This reflects the provider branch to switch to for pact verification"
          echo "env.CONSUMER_VERSION=${{ env.CONSUMER_VERSION }} # This reflects the consumer version for pact verification (generated by Pact Broker)"
          echo "env.PROVIDER_VERSION=${{ env.PROVIDER_VERSION }} # Deprecate env.PACT_PROVIDER_COMMIT. This new envvar is used for migrating GIT hash to app versioning"
          ./gradlew --build-cache verifyPacts

  ################
  # CAN-I-DEPLOY #
  ################

  can-i-deploy: # The can-i-deploy job will run as a result of a PR. It reports the pact verification statuses on all deployed environments.
    runs-on: ubuntu-latest
    if: ${{ inputs.pb-event-type == '' && needs.bump-check.outputs.is-bump == 'no' }}
    needs: [ verify-consumer-pact, bump-check, init-github-context, publish-contracts, regulated-tag-job ]
    steps:
      - name: Dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v4.0.0
        with:
          run-name: "${{ env.CAN_I_DEPLOY_RUN_NAME }}"
          workflow: .github/workflows/can-i-deploy.yaml
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN }} # github token for access to kick off a job in the private repo
          inputs: '{
            "run-name": "${{ env.CAN_I_DEPLOY_RUN_NAME }}",
            "pacticipant": "bpm",
            "version": "${{ needs.verify-consumer-pact.outputs.provider-version }}"
            }'
